canton {
    remote-sequencers.sequencer1 {
        public-api.port = 5001
        public-api.address = "sequencer1"
        admin-api.port = 5002
        admin-api.address = "sequencer1"
    }
    remote-mediators.mediator1 {
        admin-api.port = 5202
        admin-api.address = "mediator1"
    }
}
