canton {
  features.enable-testing-commands = yes

  sequencers {
    seq1 {
      public-api.port = 5018
      admin-api.port = 5019
      storage.type = memory
    }
  }

  mediators {
    med1 {
      admin-api.port = 5020
      storage.type = memory
    }
  }

  participants {
    participant1 {
      storage.type = memory
      admin-api.port = 5012
      ledger-api.port = 5011
      http-ledger-api.port = 7575
    }
    
    participant2 {
      storage.type = memory
      admin-api.port = 5022
      ledger-api.port = 5021
      http-ledger-api.port = 7576
    }
    
    participant3 {
      storage.type = memory
      admin-api.port = 5032
      ledger-api.port = 5031
      http-ledger-api.port = 7577
    }
  }
}