receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  prometheus:
    config:
      scrape_configs:
        - job_name: canton
          scrape_interval: 15s
          static_configs:
            - targets:
                - sequencer1:10013
                - mediator1:10013
                - participant1:10013
                - participant2:10013
                - participant3:10013
          metric_relabel_configs:
            - source_labels: [__name__]
              regex: "daml_health_status|daml_cache_(hits|misses|size|weight)|daml_db_storage_(general|write)_executor_(load|running)|daml_grpc_server_requests_(active|limit)|daml_participant_api_(commands_submissions_running|execution_engine_running|execution_total_running|index_updates_buffer_size|index_ledger_end_sequential_id|indexer_ledger_end_sequential_id|indexer_updates|lapi_streams_updates_sent)|daml_mediator_(outstanding_requests|max_event_age)|daml_sequencer_block_(height|delay)|daml_sequencer_client_submissions_in_flight"
              action: keep

processors:
  resource/canton:
    attributes:
      - key: service.name
        value: canton
        action: upsert
  batch:

exporters:
  otlp/aspire:
    endpoint: ${env:OTEL_EXPORTER_OTLP_ENDPOINT}
    headers:
      x-otlp-api-key: ${env:ASPIRE_API_KEY}
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [resource/canton, batch]
      exporters: [otlp/aspire]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/aspire]
